---
root: true
env:
  node: true
parserOptions:
  ecmaVersion: 2015
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'prettier'
rules:
  no-underscore-dangle: ['error', { 'allowAfterThis': true }]
  import/prefer-default-export: 'off'
